apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-shop-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cms-shop-api
  template:
    metadata:
      labels:
        app: cms-shop-api
    spec:
      initContainers:
        - name: db-migration
          image: cms-shop-api
          command: ["bun", "prisma", "db", "push"]
          env:
            - name: NODE_ENV
              value: "production"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: cms-shop-credentials
                  key: DATABASE_URL
      containers:
        - name: cms-shop-api
          image: cms-shop-api
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: cms-shop-credentials
                  key: DATABASE_URL
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              memory: "1024Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 30
